### ISSUE TITLE
Source code missing

### ISSUE THREAD

**Issue by sgparry** [fredyvonvinet/ANTLR4-Plugins-for-NetBeans#50]
I am getting the following stack trace out of netbeans when I try to build, but I cannot find the up-to-date source code for the classes mentioned in your repo - everything that is there is from 1.0 and does not correspond.
\\\\svr-file\sparry$\NetBeansProjects\JavaApplication4\nbproject\build-antlr4-impl.xml:51: Unable to find Maven POM file in classpath
	at org.nemesis.antlr.v4.ant.task.Antlr4.recoverClassPathANTLRVersion(Antlr4.java:372)
	at org.nemesis.antlr.v4.ant.task.Antlr4.execute(Antlr4.java:156)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor162.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.module.bridge.impl.BridgeImpl.run(BridgeImpl.java:286)
	at org.apache.tools.ant.module.run.TargetExecutor.run(TargetExecutor.java:555)
	at org.netbeans.core.execution.RunClassThread.run(RunClassThread.java:153)
BUILD FAILED (total time: 2 seconds)

**Comment by sgparry** [comment]
The AntTask-1.2 source code is definitely missing, which makes working on this plugin very difficult.

**Comment by sgparry** [comment]
I have posted a pull request containing reverse engineered code as a stop-gap until the real code surfaces.
